<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FirstRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FirstRepository extends EntityRepository
{
}
